tasks:
  - name: "install unzip"
    become: yes
    yum: name=unzip state=latest

  - name: "add sonarqube user"
    become: yes
    user:
      name: sonarqube
      shell: /bin/bash
      home: /home/sonarqube
      password: sonarqube

  - name: "download & unarchive sonar zip"
    become: yes
    unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.1.zip
      dest: /opt/
      remote_src: yes
      owner: sonarqube